services:
  prometheus:
    image: prom/prometheus:v2.52.0
    container_name: prometheus
    volumes:
        - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - postgres-exporter
    networks:
      - devtools

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:v0.15.0
    container_name: postgres-exporter
    environment:
      - DATA_SOURCE_NAME=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable
    ports:
      - "9187:9187"
    env_file:
      - ./postgres/.env.example
    networks:
      - devtools

  grafana:
    image: grafana/grafana-oss:10.4.2
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus
    networks:
      - devtools

  nexus:
    build:
      context: ./nexus
      dockerfile: Dockerfile
    container_name: nexus-repository
    environment:
      INSTALL4J_ADD_VM_PARAMS: "-Xms1200m -Xmx1200m -XX:+UseG1GC -XX:+UseStringDeduplication"
    volumes:
      - nexus-data:/nexus-data
    ports:
      - "8081:8081"
    networks:
      - devtools
    restart: unless-stopped

volumes:
  nexus-data:

networks:
  devtools:
    driver: bridge
  